"""Add distance type column

Revision ID: 002
Revises: 001
Create Date: 2024-06-20 22:39:47.457576

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: str | None = "001"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("distance_type_id", sa.BigInteger(), nullable=False, server_default="2")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "distance_type_id")
    # ### end Alembic commands ###
