"""Add tables to store competition versions and files

Revision ID: 003
Revises: 002
Create Date: 2024-08-21 23:23:13.032538

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: str | None = "002"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("event_dates", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("views", sa.BigInteger(), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("event_begins_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("competition_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("competition_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("server_path", sa.Text(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256_hash"),
    )
    op.create_table(
        "competition_versions",
        sa.Column("competition_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.PrimaryKeyConstraint("competition_id", "version", name="pk_competition_version"),
    )
    op.create_table(
        "content_blocks",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("competition_id", sa.BigInteger(), nullable=False),
        sa.Column("competition_version_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("competition_id"),
    )
    op.create_table(
        "content_lines",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("content_block_id", sa.BigInteger(), nullable=False),
        sa.Column("html", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("file_ids", postgresql.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column(
            "line_type",
            sa.Enum("CONTENT_LINE", "CONTENT_SUBTITLE", name="contentlinetypes"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_block_id"],
            ["content_blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_block_id"),
    )
    op.create_table(
        "files_content_lines",
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("content_line_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_line_id"],
            ["content_lines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("file_id", "content_line_id", name="pk_file_content_line"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("files_content_lines")
    op.drop_table("content_lines")
    op.drop_table("content_blocks")
    op.drop_table("competition_versions")
    op.drop_table("files")
    op.drop_table("competitions")
    # ### end Alembic commands ###
